from typing import Protocol
from churn_platform.domain.models.upload_session import PendingUploadSession
from churn_platform.domain.models.schema_mapping import SchemaMapping

class ITenantSchemaMemoryRepository(Protocol):
    async def get(self, tenant_id: str, file_names: list[str]) -> dict: ...
    async def save(self, tenant_id: str, schema: SchemaMapping) -> None: ...

class IPendingUploadRepository(Protocol):
    async def save(self, session: PendingUploadSession) -> None: ...
    async def get(self, tenant_id: str, session_id: str) -> PendingUploadSession | None: ...
    async def claim(self, tenant_id: str, session_id: str) -> bool: ...
    async def release(self, tenant_id: str, session_id: str) -> None: ...
    async def finish(self, tenant_id: str, session_id: str, result: dict) -> None: ...
    async def result(self, tenant_id: str, session_id: str) -> dict | None: ...
